//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int cart_id { get; set; }
        public int user_id { get; set; }
        public int plant_id { get; set; }
        public int quantity { get; set; }
        public System.DateTime added_date { get; set; }
    
        public virtual Plants Plants { get; set; }
        public virtual Users Users { get; set; }
    }
}
