//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discounts
    {
        public int id { get; set; }
        public int plant_id { get; set; }
        public decimal discount_percent { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string color { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Plants Plants { get; set; }
    }
}
