//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fertilization
    {
        public int id { get; set; }
        public Nullable<int> plant_id { get; set; }
        public Nullable<int> fertilizer_id { get; set; }
        public Nullable<System.DateTime> fertilization_date { get; set; }
        public Nullable<int> dosage_ml { get; set; }
    
        public virtual Fertilizers Fertilizers { get; set; }
        public virtual Plants Plants { get; set; }
    }
}
