//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int order_id { get; set; }
        public int plant_id { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Plants Plants { get; set; }
    }
}
