//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrganayzerRasteniyEntities1 : DbContext
    {
        public OrganayzerRasteniyEntities1()
            : base("name=OrganayzerRasteniyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<CareHistory> CareHistory { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<Fertilization> Fertilization { get; set; }
        public virtual DbSet<Fertilizers> Fertilizers { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<Lighting> Lighting { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<PlantLocations> PlantLocations { get; set; }
        public virtual DbSet<Plants> Plants { get; set; }
        public virtual DbSet<Reminders> Reminders { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Temperature> Temperature { get; set; }
        public virtual DbSet<UserPlants> UserPlants { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Watering> Watering { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
    }
}
