//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantLocations
    {
        public int id { get; set; }
        public Nullable<int> plant_id { get; set; }
        public Nullable<int> room_id { get; set; }
        public string window_position { get; set; }
    
        public virtual Plants Plants { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
