//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminders
    {
        public int reminder_id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> plant_id { get; set; }
        public string reminder_type { get; set; }
        public System.TimeSpan reminder_time { get; set; }
        public int frequency { get; set; }
        public string message { get; set; }
        public bool is_active { get; set; }
    
        public virtual Plants Plants { get; set; }
        public virtual Users Users { get; set; }
    }
}
