//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPlants
    {
        public int user_plant_id { get; set; }
        public int user_id { get; set; }
        public int plant_id { get; set; }
        public System.DateTime purchase_date { get; set; }
        public string care_schedule { get; set; }
        public Nullable<System.DateTime> last_care_date { get; set; }
        public string notes { get; set; }
    
        public virtual Plants Plants { get; set; }
        public virtual Users Users { get; set; }
    }
}
